// use surface.tx and config.scad generated by extract_hgt.py
include <config.scad> ;
echo(Rscale, Lat_mid, Base);
echo(Lat_metres, Long_metres);
scale([0.1,0.1,0.2])
scale ([cos(Lat_mid),1, 1/Rscale]) 
  surface(file="surface.txt",center=true,convexity=5);

